[package]
name = "spacemouse"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
structopt = "0.3.25"
evdev-rs = { version = "0.5.0", features = ["serde"] }
simplelog = "0.10.2"
anyhow = "1.0.45"
tui = "0.16.0"
indicatif = "0.16.2"
libc = "0.2.107"
serde = "1.0.130"
toml = "0.5.8"
