[package]
name = "vmouse"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
structopt = "0.3.25"
evdev-rs = { version = "0.5.0", features = ["serde"] }
simplelog = "0.10.2"
anyhow = "1.0.45"
indicatif = "0.16.2"
libc = "0.2.107"
serde = "1.0.130"
toml = "0.5.8"
ctrlc = "3.2.1"
bincode = "1.3.3"
async-std = { version = "1.10.0", features = ["attributes"] }
futures = "0.3.17"
async-ctrlc = "1.2.0"
crossbeam = "0.8.1"
smol = { version = "1.2.5", optional = false }

[[bin]]
name = "vmoused"
path = "src/daemon.rs"

[[bin]]
name = "vmousectl"
path = "src/ctl.rs"

[[bin]]
name = "vmouse"
path = "src/main.rs"

[patch.crates-io]
evdev-rs = { path = "../forks/evdev-rs" }

