[package]
name = "spacemouse"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.14"
structopt = "0.3.25"
evdev-rs = { version = "0.5.0", features = ["serde"] }
simplelog = "0.10.2"
anyhow = "1.0.45"
indicatif = "0.16.2"
libc = "0.2.107"
serde = "1.0.130"
toml = "0.5.8"

iced_native = "0.4.0"
iced_glow = "0.2.0"

[dependencies.iced]
git = "https://github.com/iced-rs/iced"
version = "0.3"
default_features = false
features = [ "glow", "glow_canvas", "glow_default_system_font" ]

[[bin]]
name = "vmouseui"
path = "src/util.rs"

[patch.crates-io]
iced_native = { git = "https://github.com/iced-rs/iced" }
iced_glow = { git = "https://github.com/iced-rs/iced" }